"""baseline schema (31 ORM tables)

Revision ID: b87a3d661918
Revises: 
Create Date: 2026-06-07 01:50:43.065884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87a3d661918'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_until_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_memory_layered',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'layer', name='uq_decision_memory_layered')
    )
    with op.batch_alter_table('decision_memory_layered', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_memory_layered_layer'), ['layer'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_memory_layered_symbol'), ['symbol'], unique=False)

    op.create_table('decision_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('as_of', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('input_snapshot_json', sa.Text(), nullable=True),
    sa.Column('agent_outputs_json', sa.Text(), nullable=True),
    sa.Column('risk_decision_json', sa.Text(), nullable=True),
    sa.Column('final_action_json', sa.Text(), nullable=True),
    sa.Column('eval_result_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_decision_run_id')
    )
    with op.batch_alter_table('decision_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_runs_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_runs_run_type'), ['run_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_runs_symbol'), ['symbol'], unique=False)

    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('report_date', sa.String(), nullable=False),
    sa.Column('disclosure_date', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('revenue_yoy', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('net_profit_yoy', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('operating_cf', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('asset_turnover', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'report_date', name='uq_fm_symbol_date')
    )
    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_metrics_disclosure_date'), ['disclosure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_metrics_symbol'), ['symbol'], unique=False)

    op.create_table('forward_theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('horizon_date', sa.String(), nullable=True),
    sa.Column('confidence_low', sa.Float(), nullable=True),
    sa.Column('confidence_high', sa.Float(), nullable=True),
    sa.Column('evidence_manifest_json', sa.Text(), nullable=True),
    sa.Column('invalidation_conditions_json', sa.Text(), nullable=True),
    sa.Column('follow_up_metrics_json', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.String(), nullable=True),
    sa.Column('review_cadence_days', sa.Integer(), nullable=True),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('theme_hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('universe_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'statement', 'horizon_date', name='uq_forward_theses_symbol_statement_horizon')
    )
    with op.batch_alter_table('forward_theses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forward_theses_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_forward_theses_symbol'), ['symbol'], unique=False)

    op.create_table('gate_b_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal_date', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('gate_pass_full', sa.Boolean(), nullable=False),
    sa.Column('gate_pass_variant', sa.Boolean(), nullable=False),
    sa.Column('card_pass', sa.Boolean(), nullable=False),
    sa.Column('ready_variant', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('entry_close', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('forward_status', sa.String(), nullable=False),
    sa.Column('realized_at', sa.String(), nullable=True),
    sa.Column('forward_return_raw', sa.Float(), nullable=True),
    sa.Column('forward_return_net', sa.Float(), nullable=True),
    sa.Column('blockers_json', sa.Text(), nullable=True),
    sa.Column('blockers_variant_json', sa.Text(), nullable=True),
    sa.Column('checks_json', sa.Text(), nullable=True),
    sa.Column('gate_b_tracker_version', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'as_of', name='uq_gate_b_obs_signal_as_of')
    )
    with op.batch_alter_table('gate_b_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gate_b_observations_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_b_observations_signal_date'), ['signal_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_gate_b_observations_symbol'), ['symbol'], unique=False)

    op.create_table('index_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('adjustment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('index_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_index_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_index_prices_symbol'), ['symbol'], unique=False)

    op.create_table('llm_usage_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_cny', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_log_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_log_created_at'), ['created_at'], unique=False)

    op.create_table('long_term_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('votes_json', sa.Text(), nullable=True),
    sa.Column('key_findings_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('constraint_eligible', sa.Boolean(), nullable=False),
    sa.Column('quality_notes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_ltl_symbol_date')
    )
    with op.batch_alter_table('long_term_labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_long_term_labels_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_long_term_labels_symbol'), ['symbol'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('float_market_cap', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('north_net_buy', sa.Float(), nullable=True),
    sa.Column('margin_balance', sa.Float(), nullable=True),
    sa.Column('large_order_net_inflow', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_ms_symbol_date')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_symbol'), ['symbol'], unique=False)

    op.create_table('memory_atoms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('trust_state', sa.String(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.String(), nullable=True),
    sa.Column('valid_to', sa.String(), nullable=True),
    sa.Column('ttl_days', sa.Integer(), nullable=True),
    sa.Column('review_case_id', sa.Integer(), nullable=True),
    sa.Column('stock_memory_item_id', sa.Integer(), nullable=True),
    sa.Column('promoted_by', sa.String(), nullable=True),
    sa.Column('refuted_by', sa.String(), nullable=True),
    sa.Column('refutation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_atoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_atoms_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_review_case_id'), ['review_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_source_ref'), ['source_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_atoms_trust_state'), ['trust_state'], unique=False)

    op.create_table('memory_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_type', sa.String(), nullable=False),
    sa.Column('profile_key', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('atom_ids_json', sa.Text(), nullable=True),
    sa.Column('trust_state', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_profiles_profile_key'), ['profile_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_profiles_profile_type'), ['profile_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_profiles_trust_state'), ['trust_state'], unique=False)

    op.create_table('memory_promotion_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_case_id', sa.Integer(), nullable=True),
    sa.Column('memory_atom_id', sa.Integer(), nullable=True),
    sa.Column('stock_memory_item_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('source_trust', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_promotion_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_promotion_candidates_source_trust'), ['source_trust'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_promotion_candidates_symbol'), ['symbol'], unique=False)

    op.create_table('memory_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('atom_ids_json', sa.Text(), nullable=True),
    sa.Column('trust_state', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_scenarios_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_scenarios_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_scenarios_trust_state'), ['trust_state'], unique=False)

    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_symbol'), ['symbol'], unique=False)

    op.create_table('pending_ai_actions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    with op.batch_alter_table('pending_ai_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_ai_actions_action'), ['action'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.String(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.String(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('realized_pnl_pct', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('atr14', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('adjustment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_price_symbol_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_symbol'), ['symbol'], unique=False)

    op.create_table('research_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('risks_json', sa.Text(), nullable=True),
    sa.Column('open_questions_json', sa.Text(), nullable=True),
    sa.Column('copilot_json', sa.Text(), nullable=True),
    sa.Column('last_signal_summary', sa.Text(), nullable=True),
    sa.Column('last_review_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', name='uq_research_state_symbol')
    )
    with op.batch_alter_table('research_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_states_symbol'), ['symbol'], unique=False)

    op.create_table('review_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('research_case_symbol', sa.String(), nullable=True),
    sa.Column('research_case_as_of', sa.String(), nullable=True),
    sa.Column('position_case_ref_json', sa.Text(), nullable=True, comment='populated when PositionCase is built (future milestone)'),
    sa.Column('outcome_correct', sa.Boolean(), nullable=True),
    sa.Column('next_day_return', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('attribution_json', sa.Text(), nullable=True),
    sa.Column('review_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of', name='uq_review_cases_symbol_as_of')
    )
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_cases_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_cases_symbol'), ['symbol'], unique=False)

    op.create_table('review_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'as_of', name='uq_review_kind_as_of')
    )
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_runs_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_runs_kind'), ['kind'], unique=False)

    op.create_table('sentiment_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('titles_hash', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('sentiment_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_cache_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_cache_titles_hash'), ['titles_hash'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('quant_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('limit_status', sa.String(), nullable=True),
    sa.Column('llm_rationale', sa.Text(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('data_timestamp', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('stock_memory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_memory_items_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_memory_items_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_memory_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_memory_items_symbol'), ['symbol'], unique=False)

    op.create_table('stocks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('theme_hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('beneficiary_tiers_json', sa.Text(), nullable=True),
    sa.Column('evidence_gaps_json', sa.Text(), nullable=True),
    sa.Column('invalidation_conditions_json', sa.Text(), nullable=True),
    sa.Column('ai_supply_chain_json', sa.Text(), nullable=True),
    sa.Column('forward_evidence_ref_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'statement', name='uq_theme_hypotheses_theme_statement')
    )
    with op.batch_alter_table('theme_hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theme_hypotheses_theme_id'), ['theme_id'], unique=False)

    op.create_table('theme_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_name', name='uq_theme_records_name')
    )
    with op.batch_alter_table('theme_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_theme_records_theme_name'), ['theme_name'], unique=False)

    op.create_table('thesis_confidence_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('as_of', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis_confidence_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesis_confidence_entries_thesis_id'), ['thesis_id'], unique=False)

    op.create_table('thesis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('kill_conditions_json', sa.Text(), nullable=True),
    sa.Column('update_cadence_days', sa.Integer(), nullable=True),
    sa.Column('research_case_symbol', sa.String(), nullable=True),
    sa.Column('research_case_as_of', sa.String(), nullable=True),
    sa.Column('review_case_ref_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'title', name='uq_thesis_records_symbol_title')
    )
    with op.batch_alter_table('thesis_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesis_records_symbol'), ['symbol'], unique=False)

    op.create_table('universe_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('universe_hash', sa.String(length=64), nullable=False),
    sa.Column('cutoff_date', sa.String(), nullable=False),
    sa.Column('market_filter', sa.String(), nullable=False),
    sa.Column('symbols_json', sa.Text(), nullable=False),
    sa.Column('n_symbols', sa.Integer(), nullable=False),
    sa.Column('provenance_completeness_json', sa.Text(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cutoff_date', 'market_filter', 'universe_hash', name='uq_universe_snapshot_cutoff_market_hash')
    )
    with op.batch_alter_table('universe_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_universe_snapshots_cutoff_date'), ['cutoff_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_universe_snapshots_universe_hash'), ['universe_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universe_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_universe_snapshots_universe_hash'))
        batch_op.drop_index(batch_op.f('ix_universe_snapshots_cutoff_date'))

    op.drop_table('universe_snapshots')
    with op.batch_alter_table('thesis_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesis_records_symbol'))

    op.drop_table('thesis_records')
    with op.batch_alter_table('thesis_confidence_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesis_confidence_entries_thesis_id'))

    op.drop_table('thesis_confidence_entries')
    with op.batch_alter_table('theme_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theme_records_theme_name'))

    op.drop_table('theme_records')
    with op.batch_alter_table('theme_hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_theme_hypotheses_theme_id'))

    op.drop_table('theme_hypotheses')
    op.drop_table('stocks')
    with op.batch_alter_table('stock_memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_memory_items_symbol'))
        batch_op.drop_index(batch_op.f('ix_stock_memory_items_status'))
        batch_op.drop_index(batch_op.f('ix_stock_memory_items_source_type'))
        batch_op.drop_index(batch_op.f('ix_stock_memory_items_memory_type'))

    op.drop_table('stock_memory_items')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_date'))

    op.drop_table('signals')
    with op.batch_alter_table('sentiment_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_cache_titles_hash'))
        batch_op.drop_index(batch_op.f('ix_sentiment_cache_symbol'))

    op.drop_table('sentiment_cache')
    with op.batch_alter_table('review_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_runs_kind'))
        batch_op.drop_index(batch_op.f('ix_review_runs_as_of'))

    op.drop_table('review_runs')
    with op.batch_alter_table('review_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_cases_symbol'))
        batch_op.drop_index(batch_op.f('ix_review_cases_as_of'))

    op.drop_table('review_cases')
    with op.batch_alter_table('research_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_states_symbol'))

    op.drop_table('research_states')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_prices_date'))

    op.drop_table('prices')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_opened_at'))

    op.drop_table('positions')
    with op.batch_alter_table('pending_ai_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_ai_actions_action'))

    op.drop_table('pending_ai_actions')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_symbol'))

    op.drop_table('news')
    with op.batch_alter_table('memory_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_scenarios_trust_state'))
        batch_op.drop_index(batch_op.f('ix_memory_scenarios_scope_type'))
        batch_op.drop_index(batch_op.f('ix_memory_scenarios_scope_key'))

    op.drop_table('memory_scenarios')
    with op.batch_alter_table('memory_promotion_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_promotion_candidates_symbol'))
        batch_op.drop_index(batch_op.f('ix_memory_promotion_candidates_source_trust'))

    op.drop_table('memory_promotion_candidates')
    with op.batch_alter_table('memory_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_profiles_trust_state'))
        batch_op.drop_index(batch_op.f('ix_memory_profiles_profile_type'))
        batch_op.drop_index(batch_op.f('ix_memory_profiles_profile_key'))

    op.drop_table('memory_profiles')
    with op.batch_alter_table('memory_atoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_atoms_trust_state'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_source_type'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_source_ref'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_scope_type'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_scope_key'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_review_case_id'))
        batch_op.drop_index(batch_op.f('ix_memory_atoms_memory_type'))

    op.drop_table('memory_atoms')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_date'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('long_term_labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_long_term_labels_symbol'))
        batch_op.drop_index(batch_op.f('ix_long_term_labels_date'))

    op.drop_table('long_term_labels')
    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_log_bucket'))

    op.drop_table('llm_usage_log')
    with op.batch_alter_table('index_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_index_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_index_prices_date'))

    op.drop_table('index_prices')
    with op.batch_alter_table('gate_b_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gate_b_observations_symbol'))
        batch_op.drop_index(batch_op.f('ix_gate_b_observations_signal_date'))
        batch_op.drop_index(batch_op.f('ix_gate_b_observations_as_of'))

    op.drop_table('gate_b_observations')
    with op.batch_alter_table('forward_theses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forward_theses_symbol'))
        batch_op.drop_index(batch_op.f('ix_forward_theses_status'))

    op.drop_table('forward_theses')
    with op.batch_alter_table('financial_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_metrics_symbol'))
        batch_op.drop_index(batch_op.f('ix_financial_metrics_report_date'))
        batch_op.drop_index(batch_op.f('ix_financial_metrics_disclosure_date'))

    op.drop_table('financial_metrics')
    with op.batch_alter_table('decision_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_runs_symbol'))
        batch_op.drop_index(batch_op.f('ix_decision_runs_run_type'))
        batch_op.drop_index(batch_op.f('ix_decision_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_decision_runs_as_of'))

    op.drop_table('decision_runs')
    with op.batch_alter_table('decision_memory_layered', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_memory_layered_symbol'))
        batch_op.drop_index(batch_op.f('ix_decision_memory_layered_layer'))

    op.drop_table('decision_memory_layered')
    op.drop_table('chat_sessions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
